# Generated by Django 4.0.4 on 2022-05-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
