# Generated by Django 4.0.4 on 2022-05-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_alter_paciente_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data',
            field=models.DateField(),
        ),
    ]
